from distutils.command.build_scripts import first_line_re
from mgen import main
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time
#from pygame import mixer
import play_music
from collections import Counter

# emotion classes
# 0 anger
# 1 contempt
# 2 disgust
# 3 fear
# 4 happy
# 5 neutral
# 6 sad
# 7 surprise

# def generate_music():

#     # Load the emotion list generated by the video
#     emo = pd.read_csv('emotext.csv')
#     reader = emo.columns.tolist()
#     #emotions = [int(i) for i in reader[0]]
#     emotions =[1,1,1,1,1,1,3,3,4,4,4,4,4,4,4]

#     count = 0
#     now = emotions[0]
#     for i in range(len(emotions)):
        
#         if now == emotions[count]:
            # count += 1
            # if count >= 5:
                
            #     # 0 anger
            #     if now == 0:
            #         soundfile= '1647304532/fear.mp3'

            #     # 1 contempt
            #     elif now == 1:
            #         soundfile= '1647304532/fear.mp3'

            #     # 2 disgust
            #     elif now == 2:
            #         soundfile= '1647304532/fear.mp3'

            #     # 3 fear
            #     elif now == 3:
            #         soundfile= '1647304532_fear/fear.mp3'

                # 4 happy
        #         elif now == 4:
        #             soundfile= '1647304532/fear.mp3'

        #         # 5 neutral
        #         elif now == 5:
        #             soundfile= '1647456249_neutral/neutral.mp3'

        #         # 6 sad
        #         elif now == 6:
        #             soundfile= '1647304532/fear.mp3'

        #         # 7 surprise
        #         elif now == 7:
        #             soundfile= '1647304532/fear.mp3'

        #         play_music.play(soundfile=soundfile, duration_secs=5)
        #         now = emotions[count]
        #         emotions = emotions[count:]
        #         count = 0

        # elif emotions[count] != now:
        #     now = emotions[count]
        #     emotions = emotions[count:]
        #     count=0


# generate_music()

          

# emotions =[1,1,1,1,1,1,3,3,4,4,4,4,4,4,4]


def Most_Common(emotions):
    data = Counter(emotions)
    first_emo = data.most_common(1)[0]#[0]
    second_emo = data.most_common(2)[1]#[0]
    return [first_emo, second_emo]

# print(Most_Common(emotions)[0][0])


def music_first_emotions():

    # Load the emotion list generated by the video
    emo = pd.read_csv('emotext.csv')
    reader = emo.columns.tolist()
    emotions = [int(i) for i in reader[0]]
    # emotions =[5,5,5,5,5,5,5,5,3,4,4,4,4,4,4,4]

    # Most_Common(emotions)
    first = Most_Common(emotions)[0]
    
    # 0 anger
    if first[0] == 0:
        soundfile_1 = 'djceci/anger.mp3' 

    # 1 contempt
    elif first[0] == 1:
        soundfile_1 = 'djceci/sad.mp3' ##

    # 2 disgust
    elif first[0] == 2:
        soundfile_1 = 'djceci/surprise.mp3' ##

    # 3 fear
    elif first[0]  == 3:
        soundfile_1 = 'djceci/fear.mp3'

    # 4 happy
    elif first[0]  == 4:
        soundfile_1 = 'djceci/happy.mp3' 

    # 5 neutral
    elif first[0] == 5:
        soundfile_1 = 'djceci/neutral.mp3'

    # 6 sad
    elif first[0]  == 6:
        soundfile_1 = 'djceci/sad.mp3'

    # 7 surprise
    elif first[0] == 7:
        soundfile_1 = 'djceci/surprise.mp3'

    play_music.play(soundfile= soundfile_1, duration_secs =20)



def music_second_emotions():

    # Load the emotion list generated by the video
    emo = pd.read_csv('emotext.csv')
    reader = emo.columns.tolist()
    emotions = [int(i) for i in reader[0]]
    # emotions =[5,5,5,5,5,5,5,5,3,4,4,4,4,4,4,4]

    # Most_Common(emotions)
    second = Most_Common(emotions)[1]

    # 0 anger
    if second[0] == 0:
        soundfile_2 = 'djceci/anger.mp3' 

    # 1 contempt
    elif second[0] == 1:
        soundfile_2 = 'djceci/sad.mp3' ##

    # 2 disgust
    elif second[0] == 2:
        soundfile_2 = 'djceci/surprise.mp3' ##

    # 3 fear
    elif second[0]  == 3:
        soundfile_2 = 'djceci/fear.mp3'

    # 4 happy
    elif second[0]  == 4:
        soundfile_2 = 'djceci/happy.mp3' 

    # 5 neutral
    elif second[0] == 5:
        soundfile_2 = 'djceci/neutral.mp3'

    # 6 sad
    elif second[0]  == 6:
        soundfile_2 = 'djceci/sad.mp3'

    # 7 surprise
    elif second[0] == 7:
        soundfile_2 = 'djceci/surprise.mp3'

    play_music.play(soundfile= soundfile_2, duration_secs =20)



# music_first_emotions()
# music_second_emotions()