import pandas as pd
import numpy as np
from collections import Counter


def Most_Common(emotions):
    data = Counter(emotions)
    first_emo = data.most_common(1)[0]#[0]
    second_emo = data.most_common(2)[1]#[0]
    return [first_emo, second_emo]


def write_two_emotions():

    # Load the emotion list generated by the video
    emo = pd.read_csv('emotext.csv')
    reader = emo.columns.tolist()
    emotions = [int(i) for i in reader[0]]
    # emotions =[5,5,5,5,5,5,5,5,3,4,4,4,4,4,4,4]

    first = Most_Common(emotions)[0][0]
    first_n = Most_Common(emotions)[0][1]
    first_ratio = round((first_n/len(emotions))*100, 2)
    first_perc = str(first_ratio) + '%'

    # 0 anger
    if first == 0:
        first_em = 'Anger'

    # 1 contempt
    elif first == 1:
        first_em = 'Contempt'

    # 2 disgust
    elif first == 2:
        first_em = 'Disgust'

    # 3 fear
    elif first  == 3:
        first_em = 'Fear'

    # 4 happy
    elif first  == 4:
        first_em = 'Happy'

    # 5 neutral
    elif first == 5:
        first_em = 'Neutral'

    # 6 sad
    elif first  == 6:
        first_em = 'Sad'

    # 7 surprise
    elif first == 7:
        first_em = 'Surprise'

    
    second = Most_Common(emotions)[1][0]
    second_n = Most_Common(emotions)[1][1]
    second_ratio = round((second_n/len(emotions))*100, 2)
    second_perc = str(second_ratio) + '%'

    # 0 anger
    if second == 0:
        second_em = 'Anger'

    # 1 contempt
    elif second == 1:
        second_em = 'Contempt'

    # 2 disgust
    elif second == 2:
        second_em = 'Disgust'

    # 3 fear
    elif second  == 3:
        second_em = 'Fear'

    # 4 happy
    elif second  == 4:
        second_em = 'Happy'

    # 5 neutral
    elif second == 5:
        second_em = 'Neutral'

    # 6 sad
    elif second  == 6:
        second_em = 'Sad'

    # 7 surprise
    elif second == 7:
        second_em = 'Surprise'

    return f'{first_em}: {first_perc}', f'{second_em}: {second_perc}'

# write_two_emotions()